### ISSUE TITLE
giving away your webstorm key is probably bad

### ISSUE THREAD

**Issue by mkoryak** [ronperris/learntocodeoc#2]
it comes up in github search results. 

https://github.com/search?l=markdown&o=desc&q=%3D%3D%3D%3D%3D+LICENSE+BEGIN+AND+webstorm&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93

**Comment by ronperris** [comment]
Thanks for the advice. I'll consider hiding it.
